/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors')

module.exports = {
   content: [
      './node_modules/flowbite-react/**/*.{js,jsx,ts,tsx}',
      './src/**/*.{ts,tsx}',
      './public/**/*.html',
      './node_modules/@material-tailwind/react/components/**/*.{js,ts,jsx,tsx}',
      './node_modules/@material-tailwind/react/theme/components/**/*.{js,ts,jsx,tsx}',
   ],
   darkMode: 'class',
   theme: {
      extend: {
         screens: {
            xs: '240px',
         },
         colors: {
            primary: {
               50: '#eff6ff',
               100: '#dbeafe',
               200: '#bfdbfe',
               300: '#93c5fd',
               400: '#60a5fa',
               500: '#3b82f6',
               600: '#2563eb',
               700: '#1d4ed8',
               800: '#1e40af',
               900: '#1e3a8a',
               950: '#172554',
            },
            astronaut: {
               50: '#f1f7fd',
               100: '#dfeefa',
               200: '#c5e2f8',
               300: '#9ecff2',
               400: '#6fb5eb',
               500: '#4e97e3',
               600: '#397bd7',
               700: '#3067c5',
               800: '#2d55a0',
               900: '#244070',
               950: '#1d2d4e',
            },
            ceruleanblue: {
               50: '#f0f5fe',
               100: '#dee7fb',
               200: '#c4d7f9',
               300: '#9bbcf5',
               400: '#6c99ee',
               500: '#4975e8',
               600: '#3458dc',
               700: '#2b45ca',
               800: '#293aa4',
               900: '#263582',
               950: '#1c224f',
            },
            blueviolet: {
               50: '#f4f6fa',
               100: '#e5e9f4',
               200: '#d1d9ec',
               300: '#b2c0de',
               400: '#8da1cd',
               500: '#7183c0',
               600: '#5b69b0',
               700: '#535ca2',
               800: '#484d85',
               900: '#3d426b',
               950: '#292b42',
            },
            scarlet: {
               50: '#fff4ec',
               100: '#ffe5d3',
               200: '#ffc7a5',
               300: '#ffa06d',
               400: '#ff6d32',
               500: '#ff460a',
               600: '#f52900',
               700: '#cc1a02',
               800: '#a1160b',
               900: '#82150c',
               950: '#460604',
            },
         },
      },
      fontFamily: {
         body: [
            'Inter',
            'ui-sans-serif',
            'system-ui',
            '-apple-system',
            'system-ui',
            'Segoe UI',
            'Roboto',
            'Helvetica Neue',
            'Arial',
            'Noto Sans',
            'sans-serif',
            'Apple Color Emoji',
            'Segoe UI Emoji',
            'Segoe UI Symbol',
            'Noto Color Emoji',
         ],
         sans: [
            'Inter',
            'ui-sans-serif',
            'system-ui',
            '-apple-system',
            'system-ui',
            'Segoe UI',
            'Roboto',
            'Helvetica Neue',
            'Arial',
            'Noto Sans',
            'sans-serif',
            'Apple Color Emoji',
            'Segoe UI Emoji',
            'Segoe UI Symbol',
            'Noto Color Emoji',
         ],
      },
   },
   plugins: [
      require('flowbite/plugin')({
         charts: true,
         forms: true,
         tooltips: true,
      }),
      require('@tailwindcss/typography'),
      require('tailwind-bootstrap-grid')({
         containerMaxWidths: { sm: '540px', md: '720px', lg: '960px', xl: '1140px' },
      }),
   ],
}
