/** @format */

'use client'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'flowbite'
import React, { StrictMode, useEffect } from 'react'
import theme from '@/components/layouts/flowbite-theme'
import { Flowbite } from 'flowbite-react'
import './globals.css'
import '@/styles/style.scss'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import NextTopLoader from 'nextjs-toploader'
import { Provider } from 'react-redux'
import ReduxProvider from '@/components/layouts/redux-provider'
import { getSessionStorages, isEmpty } from '@/utils/_function/utils'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
    useEffect(() => {
        if (isEmpty(getSessionStorages('sidebar-size'))) sessionStorage.setItem('sidebar-size', 'sm')
    }, [])
    return (
        <html lang="en">
            <ReduxProvider>
                <StrictMode>
                    <body className={inter.className + ` dark:bg-gray-900 dark:border-gray-800 dark:border-gray-700 bg-ceruleanblue-50 `}>
                        <NextTopLoader color="#2299DD" initialPosition={0.08} crawlSpeed={200} height={3} crawl={true} showSpinner={true} easing="ease" speed={200} shadow="0 0 10px #2299DD,0 0 5px #2299DD" />
                        <ToastContainer />
                        <Flowbite theme={{ theme }}>{children}</Flowbite>
                    </body>
                </StrictMode>
            </ReduxProvider>
        </html>
    )
}
