/** @format */

interface IFreightCose {
   in_weight_one?: number | null
   out_weight_one?: number | null
   min_berat_one?: number | null
   priece_one?: number | null
   in_weight_two?: number | null
   out_weight_two?: number | null
   min_berat_two?: number | null
   priece_two?: number | null
   min_charge?: number | null
   berat?: number | null
   tarif_smu?: number | null
   ppn?: number | null
   heandling_fee?: number | null
   biaya_admin?: number | null
   surcharge_ac?: number | null
   service_fee?: number | null
   sewa_gedung?: number | null
   other_cfc?: number | null
   regulated_agent?: number | null
   cargo_cash_msc?: number | null
   basio_storage_zbc?: number | null
   total?: number | null
   tarif_smu_plus?: number | null
   ppn_plus?: number | null
   total_plus?: number | null
   keterangan?: string | null
   lead_time?: string | null
   payment_period?: number | null
   capacity?: number | null
   tralling_origin?: string | null
   container?: string | null
   stuffing?: string | null
   thc?: string | null
   lolo?: string | null
   bill_ofladding?: string | null
   segel?: string | null
   materai?: string | null
   surcharge_freight?: string | null
   surcharge_alih_kapal?: string | null
   asdp?: string | null
   other_hand_fees?: string | null
   storage_alih_kapal?: string | null
   trailer_destination?: string | null
   amount?: string | null
   leadtime?: string | null
   hpp?: string | null
}
